# Generated by Django 2.0.3 on 2018-04-04 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serum',
            fields=[
                ('local_sample_id', models.SmallIntegerField()),
                ('coll_num', models.SmallIntegerField()),
                ('sample_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('birth_date', models.IntegerField()),
                ('age_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender_1ismale_value', models.PositiveIntegerField()),
                ('coll_date', models.CharField(max_length=10)),
                ('day_value', models.IntegerField()),
                ('month_value', models.IntegerField()),
                ('year', models.IntegerField()),
                ('results_file_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Serum',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Site',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=40)),
                ('khoa', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Ward',
            },
        ),
        migrations.CreateModel(
            name='Freezer',
            fields=[
                ('sample_auto_id', models.CharField(blank=True, max_length=10, null=True)),
                ('study_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Serum')),
                ('original_age', models.IntegerField()),
                ('gender_1ismale_value', models.PositiveIntegerField()),
                ('coll_date', models.CharField(max_length=10)),
                ('sample_type', models.CharField(blank=True, max_length=30, null=True)),
                ('aliquot_no', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.SmallIntegerField(blank=True, null=True)),
                ('freezer_section_name', models.CharField(max_length=10)),
                ('subdivision_1_position', models.CharField(max_length=1)),
                ('subdivision_2_position', models.IntegerField()),
                ('subdivision_3_position', models.IntegerField()),
                ('subdivision_4_position', models.IntegerField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sboapp.Site')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sboapp.Ward')),
            ],
            options={
                'db_table': 'Freezer',
            },
        ),
        migrations.AddField(
            model_name='serum',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sboapp.Site'),
        ),
        migrations.AddField(
            model_name='serum',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sboapp.Ward'),
        ),
    ]
