# Generated by Django 2.0.3 on 2018-05-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serum',
            old_name='birth_date',
            new_name='birth_year',
        ),
    ]
