# Generated by Django 2.0.3 on 2018-05-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0002_auto_20180504_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elisa',
            fields=[
                ('result_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('elisa_day', models.IntegerField()),
                ('elisa_month', models.IntegerField()),
                ('elisa_year', models.IntegerField()),
            ],
            options={
                'db_table': 'Elisa',
            },
        ),
        migrations.CreateModel(
            name='Pma',
            fields=[
                ('ag_array_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tray', models.CharField(max_length=5)),
                ('batch_id', models.CharField(max_length=4)),
                ('start_dilution', models.SmallIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=20)),
                ('processed_day', models.IntegerField()),
                ('processed_month', models.IntegerField()),
                ('processed_year', models.IntegerField()),
                ('batch_sent_id', models.IntegerField()),
                ('scanned_day', models.IntegerField()),
                ('scanned_month', models.IntegerField()),
                ('scanned_year', models.IntegerField()),
                ('panbio_unit', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Pma',
            },
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='coll_date',
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='gender_1ismale_value',
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='original_age',
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='sample_auto_id',
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='site',
        ),
        migrations.RemoveField(
            model_name='freezer',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='serum',
            name='local_sample_id',
        ),
        migrations.RemoveField(
            model_name='serum',
            name='results_file_id',
        ),
        migrations.CreateModel(
            name='Chik_elisa',
            fields=[
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Elisa')),
                ('sample_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('negative_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('cut_off_1_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('cut_off_2_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('positive_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('cut_off', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('novatech_units', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('result', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Chik_elisa',
            },
        ),
        migrations.CreateModel(
            name='Dengue_elisa',
            fields=[
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Elisa')),
                ('sample_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('negative_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('positive_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('calibrator_1_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('calibrator_2_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('calibrator_3_absorbance', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('cal_factor', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('cut_off', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('positive_cut_off_ratio', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('dengue_index', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('panbio_unit', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('result', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Dengue_elisa',
            },
        ),
        migrations.CreateModel(
            name='Pma_result',
            fields=[
                ('ag_array_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Pma')),
                ('chikv_e1_mutant', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('chikv_e2', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv1_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv2_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv3_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv4_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('jev_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('slev_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('tbev_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('wnv_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('yfv_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('zikv_brasil_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('zikv_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Pma_result',
            },
        ),
        migrations.CreateModel(
            name='Rickettsia_elisa',
            fields=[
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Elisa')),
                ('scrub_typhus', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('typhus', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Rickettsia_elisa',
            },
        ),
        migrations.AddField(
            model_name='pma',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sboapp.Serum'),
        ),
        migrations.AddField(
            model_name='elisa',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sboapp.Serum'),
        ),
    ]
