# Generated by Django 2.0.3 on 2018-05-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0003_auto_20180504_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='serum',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serum',
            name='local_sample_id',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serum',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
