# Generated by Django 2.0.3 on 2018-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0005_auto_20180515_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='site',
            new_name='site_id',
        ),
    ]
