# Generated by Django 2.0.3 on 2018-05-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0007_auto_20180521_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rickettsia_elisa',
            old_name='result',
            new_name='result_id',
        ),
        migrations.RemoveField(
            model_name='chik_elisa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dengue_elisa',
            name='id',
        ),
        migrations.AddField(
            model_name='chik_elisa',
            name='result_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Elisa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dengue_elisa',
            name='result_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Elisa'),
            preserve_default=False,
        ),
    ]
