# Generated by Django 2.0.3 on 2018-05-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0008_auto_20180521_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='elisa',
            name='pathogen',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
