# Generated by Django 2.0.3 on 2018-06-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0009_elisa_pathogen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rickettsia_elisa',
            old_name='result_id',
            new_name='result',
        ),
        migrations.RemoveField(
            model_name='chik_elisa',
            name='result_id',
        ),
        migrations.RemoveField(
            model_name='dengue_elisa',
            name='result_id',
        ),
        migrations.AddField(
            model_name='chik_elisa',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dengue_elisa',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
