# Generated by Django 2.0.3 on 2018-06-04 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0010_auto_20180604_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chik_elisa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dengue_elisa',
            name='id',
        ),
        migrations.AddField(
            model_name='chik_elisa',
            name='result_chik',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dengue_elisa',
            name='result_dengue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='chik_elisa',
            name='result',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Elisa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dengue_elisa',
            name='result',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='sboapp.Elisa'),
            preserve_default=False,
        ),
    ]
