# Generated by Django 2.0.3 on 2018-06-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0011_auto_20180604_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elisa',
            old_name='sample',
            new_name='sample_id',
        ),
    ]
