# Generated by Django 2.0.3 on 2018-06-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0014_auto_20180605_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rickettsia_elisa',
            old_name='result',
            new_name='result_id',
        ),
    ]
