# Generated by Django 2.0.3 on 2018-06-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0015_auto_20180605_0406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rickettsia_elisa',
            old_name='result_id',
            new_name='result',
        ),
    ]
