# Generated by Django 2.0.3 on 2018-06-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0016_auto_20180605_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chik_elisa',
            name='result',
        ),
        migrations.RemoveField(
            model_name='dengue_elisa',
            name='result',
        ),
        migrations.RemoveField(
            model_name='rickettsia_elisa',
            name='result',
        ),
        migrations.DeleteModel(
            name='Chik_elisa',
        ),
        migrations.DeleteModel(
            name='Dengue_elisa',
        ),
        migrations.DeleteModel(
            name='Rickettsia_elisa',
        ),
    ]
