# Generated by Django 2.0.3 on 2018-06-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0019_auto_20180606_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chik_elisa',
            old_name='result',
            new_name='elisa',
        ),
        migrations.RenameField(
            model_name='dengue_elisa',
            old_name='result',
            new_name='elisa',
        ),
        migrations.RenameField(
            model_name='rickettsia_elisa',
            old_name='result',
            new_name='elisa',
        ),
    ]
