# Generated by Django 2.0.3 on 2018-06-06 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0021_auto_20180606_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chik_elisa',
            name='elisa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sboapp.Elisa'),
        ),
    ]
