# Generated by Django 2.0.3 on 2018-06-06 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0023_auto_20180606_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dengue_elisa',
            name='elisa',
            field=models.OneToOneField(db_column='elisa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sboapp.Elisa'),
        ),
        migrations.AlterField(
            model_name='rickettsia_elisa',
            name='elisa',
            field=models.OneToOneField(db_column='elisa', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sboapp.Elisa'),
        ),
    ]
