# Generated by Django 2.0.3 on 2018-06-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0024_auto_20180606_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serum',
            name='age_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='serum',
            name='age_min',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
