# Generated by Django 2.0.3 on 2018-06-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0025_auto_20180606_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pma',
            fields=[
                ('result_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('ag_array_id', models.CharField(max_length=25)),
                ('tray', models.CharField(max_length=5)),
                ('batch_id', models.CharField(max_length=4)),
                ('start_dilution', models.SmallIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=20, null=True)),
                ('processed_day', models.IntegerField(null=True)),
                ('processed_month', models.IntegerField(null=True)),
                ('processed_year', models.IntegerField(null=True)),
                ('batch_sent_id', models.IntegerField(null=True)),
                ('scanned_day', models.IntegerField(null=True)),
                ('scanned_month', models.IntegerField(null=True)),
                ('scanned_year', models.IntegerField(null=True)),
                ('panbio_unit', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Pma',
            },
        ),
        migrations.CreateModel(
            name='Pma_result',
            fields=[
                ('pma', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sboapp.Pma')),
                ('chikv_e1_mutant', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('chikv_e2', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv1_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv2_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv3_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('dv4_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('jev_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('slev_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('tbev_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('wnv_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('yfv_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('zikv_brasil_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('zikv_ns1', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'Pma_result',
            },
        ),
        migrations.AddField(
            model_name='pma',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sboapp.Serum'),
        ),
    ]
