# Generated by Django 2.0.3 on 2018-07-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0026_auto_20180607_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serum',
            name='age',
        ),
        migrations.RemoveField(
            model_name='serum',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='serum',
            name='original_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serum',
            name='status',
            field=models.CharField(default='Available', max_length=11),
        ),
        migrations.AlterField(
            model_name='pma_result',
            name='pma',
            field=models.OneToOneField(db_column='pma', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sboapp.Pma'),
        ),
    ]
