# Generated by Django 2.0.3 on 2018-07-30 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0028_auto_20180723_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='serum',
            name='import_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serum',
            name='import_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
