# Generated by Django 2.0.3 on 2018-07-30 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sboapp', '0029_auto_20180730_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezer',
            name='import_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freezer',
            name='import_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
